
name: Build Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PG_VERSION: 13
    steps:
      - uses: actions/checkout@master

      - name: Log in to the GHCR
        uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: remove ustc mirror
        run: |
          sed -i 's/RUN sed -i/#RUN sed -i/g' ./Dockerfile
        id: remove-mirror

      - name: Set up image name
        run: |
          GHRC_IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}:${{ env.PG_VERSION }}" | tr '[:upper:]' '[:lower:]')
          GHRC_IMAGE_NAME_LATEST=$(echo "ghcr.io/${{ github.repository }}:latest" | tr '[:upper:]' '[:lower:]')
          echo "::set-output name=GHRC_IMAGE_NAME::$GHRC_IMAGE_NAME"
          echo "::set-output name=GHRC_IMAGE_NAME_LATEST::$GHRC_IMAGE_NAME_LATEST"
        id: image-name

      - name: Build dasbboard image And Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          build-args: PG_VERSION=${{ env.PG_VERSION }}
          tags: |
            ${{ steps.image-name.outputs.GHRC_IMAGE_NAME }}
            ${{ steps.image-name.outputs.GHRC_IMAGE_NAME_LATEST }}

  
